### ISSUE TITLE
Sprint 1 - Tarea 3 - Creación de un repositorio de ejemplo dentro de la organización, donde cada miembro evidencie un commit

### ISSUE THREAD

**Issue by Reyezonia** [Reyezonia/Pilotos#3]
Realizar cada uno un commit en el repositorio dentro de la organización. lo pueden hacer en el archivo Readme alguna modificación o similar para que quede el commit. 
Todos los integrantes deben realizar cambios en las fuentes de forma que se vean reflejados en el historial.

**Comment by Reyezonia** [comment]
los integrantes del equipo realizan la tarea 3, se entrega el documento sprint 1 en la plataforma

**Comment by ACAC0218** [comment]
Calificación sprint #1 lista
